name: CI
on:
  push:
    branches:
      - master
    tags:
      - "!*"
    paths-ignore:
      - "**.md"
  pull_request:

env:
  go-version: "1.16"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "${{ env.go-version }}"
      - name: cache
        uses: actions/cache@v3.0.8
        id: cache-go
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ env.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ env.go-version }}
      - name: Get dependencies
        if: steps.cache-go.outputs.cache-hit != 'true'
        run: |
          go get -v -t -d ./...
      - name: Test
        run: |
          go test -v ./...
      - name: Build
        run: |
          go build -v ./main.go

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: latest

  deploy:
    needs:
      - test
      - lint
    if: contains(github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.RENDER_COM_DEPLOY_HOOK_URL }}
          method: 'GET'
