name: CI
on:
  push:
    branches:
      - master
    tags:
      - "!*"
    paths-ignore:
      - "**.md"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache: true
      - name: Get dependencies
        run: |
          go mod download
      - name: Test
        run: |
          date
          go test -v ./...
        env:
          TWITTER_USER_NAME: ${{ secrets.TWITTER_USER_NAME }}
          TWITTER_USER_PASSWORD: ${{ secrets.TWITTER_USER_PASSWORD }}
          TWITTER_USER_MFA_SECRET: ${{ secrets.TWITTER_USER_MFA_SECRET }}
      - name: Build
        run: |
          go build -v ./main.go

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          version: latest

  deploy:
    needs:
      - test
      - lint
    if: contains(github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.RENDER_COM_DEPLOY_HOOK_URL }}
          method: 'GET'
