name: CI
on:
  push:
    branches:
      - master
    tags:
      - "!*"
    paths-ignore:
      - "**.md"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.14.5"
      - name: cache
        uses: actions/cache@v2
        id: cache-go
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Get dependencies
        if: steps.cache-go.outputs.cache-hit != 'true'
        run: |
          go get -v -t -d ./...
      - name: Test
        run: |
          go test -v ./...
      - name: Build
        run: |
          go build -v ./main.go

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.28

  deploy:
    needs:
      - test
      - lint
    if: contains(github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.2.6
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "twitter-like-feed"
          heroku_email: ${{ secrets.HEROKU_USER_EMAIL }}
          usedocker: true
